# Yarn 4 Configuration

# Utilise la structure classique node_modules pour une meilleure compatibilité
nodeLinker: node-modules

# Permet l'exécution des scripts de build
enableScripts: true

# Cache des packages pour les installations plus rapides
compressionLevel: mixed
